management:
  endpoint:
    jolokia.config.debug: true
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: '*'
  metrics.export.prometheus.enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
  url: "jdbc:postgresql://localhost:5432/public-notification"
  username: "postgres"
  password: "password"

  # The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"

  # Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: "update"

---
spring.profile: docker
spring.datasource.url: "jdbc:postgresql://Michaels-MacBook-Pro-2.local:5432/public-notification"

---
spring.profile: aws